services:
  - type: web
    name: secureshield-backend
    env: node
    plan: starter
    region: oregon
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health
    # Uncomment to attach a persistent disk (paid tier required)
    # disk:
    #   name: data
    #   mountPath: /opt/render/project/src/data
    #   sizeGB: 1
